config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/index'
  root 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ROR</title>

	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	  <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
	  <link href="https://fonts.googleapis.com/css?family=Rationale" rel="stylesheet">

	  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <%= csrf_meta_tags %>

  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container">
         <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', static_pages_about_path %></li>
          <li><%= link_to 'Contact', static_pages_contact_path %> </li>
          <li><%= link_to 'Products', products_path %>
        </ul>
      </div>
    </nav>
  
    <%= yield %>
    
    <div class="navbar navbar-default navbar-static-bottom">
      <div class="container footer">
        <span class="navbar-text">
          &copy James Thomas Haggerty
        </span>
      </div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>ra
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

<div class="actions">
    <%= f.submit %>
</div>

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing products!</h1>

<br>

<!--<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.colour %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>-->

<div class="container-fluid">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-sm-2 col-md-4">
        <a href=""><h1><%= product.name %></h1></a>
        <%= image_tag(product.image_url, class: "img-responsive") %>
        <p class="description"><%= product.description %></p>
        <p class="priced"><%= product.price %></p>
      </div><!-- /col -->
    <% end %>
  </div>
</div>



<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p class="name">
  <p class="title">Name:</p>
  <%= @product.name %>
</p>

<p class="name">
  <p class= "title">Today's lovely product:</p>
  <%= @product.description %>
</p>

<p class="name">
  <p class= "title">Where the picture lives:</p>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> /
<%= link_to 'Back', products_path %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>


<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<h1> Hello, this is James </h1>


<p> With this app, we will be bringing the occult underworld to your finger tips with our new app, "Weird Occult Things R Us." We are very dedicated to helping you reach your goal of becoming that weird guy down the street who collects dolls that look like they're from the mouth of hell. </p>

app/views/static_pages/contact.html.erb
<h1> Welcome to our contact page </h1>

<h2> You can reach us at our number #666-123-4567. </h2>
<h2> You can also find us at www.weirdoccultshit.com </h2>

app/views/static_pages/index.html.erb
<h1> Welcome to James' occult merchandise </h1>
<h2> Your choice for weird, old, occult things </h2>
 <%= image_tag("cthulu.jpg", class: "img-responsive", id: "cthulu") %>